
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=eventuser
quarkus.datasource.password=eventpass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/eventdb


quarkus.hibernate-orm.database.generation=drop-and-create


quarkus.hibernate-orm.log.sql=true


quarkus.swagger-ui.always-include=true

# Keycloak / OIDC configuration
quarkus.oidc.auth-server-url=http://localhost:8180/realms/tango-events
quarkus.oidc.client-id=tango-events-app
quarkus.oidc.credentials.secret=eBNkJyQz2LY7nya1GlWJAAEDjrMp1oB2
quarkus.oidc.application-type=service

# Allow Swagger UI to work without auth
quarkus.http.auth.permission.authenticated.paths=/events/*,/rsvp/*,/users/*
quarkus.http.auth.permission.authenticated.policy=authenticated

# Swagger UI Keycloak integration
quarkus.swagger-ui.oauth-client-id=tango-events-app
quarkus.swagger-ui.oauth2-redirect-url=http://localhost:8080/q/swagger-ui
quarkus.openapi.security-scheme=oauth2-implicit
quarkus.openapi.oauth2-implicit-refresh-url=http://localhost:8180/realms/tango-events/protocol/openid-connect/token
quarkus.openapi.oauth2-implicit-authorization-url=http://localhost:8180/realms/tango-events/protocol/openid-connect/auth